### ISSUE TITLE
[Bug] allowProcess Property toggle not working

### ISSUE THREAD

**Issue by Boogalew** [pqina/angular-filepond#10]
allowProcces Property does not enable or disable the Process button after uploading a file after following the Filepond Documentation

Typescript pondOptions:
`
pondOptions: FilePondOptions = {
    acceptedFileTypes: [*/List of accepted file types/*],
    allowProcess: true,
    allowBrowse: true,
    allowMultiple: true,
    allowRevert: true,
    labelIdle: 'Drop files here...',
    server: {
      process: (fieldName, file, metadata, load, error, progress, abort, transfer, options) => {
       //logic for handling proccess uploading
      },
      revert: (uniqueFileId, load, error) => {
      //logic for reverting
      },
    },
  }
`

html:
`
    <div class="modal-body data-scroll-container">
        <file-pond #myPond 
        [options]="pondOptions" >
        </file-pond>
    </div>
`

- Device: OMEN by HP 45L Gaming Desktop GT22-0xxx
- OS: Windows 11 Enterprise
- Browser: Version 124.0.6367.61
- Angular version: 15.2.2

**Comment by rikschennink** [comment]
Hi, This property is not reactive, so once it's set it cannot be updated. This will all change in v5.
