### ISSUE TITLE
Error during load

### ISSUE THREAD

**Issue by aitorllj93** [pqina/angular-filepond#3]
Hi, I got this error when trying to load your component in edit forms:

![seleccion_018](https://user-images.githubusercontent.com/5903438/39765248-ae43fb76-52e1-11e8-985c-7842372b358e.png)

```ts
<FilePond
   #fileUploader
  allowReplace="false"
  allowMultiple="false"
  [server]="fileUploadServer"
  [files]="files"
  (onprocessfile)="onProcessFile($event)"
  (onremovefile)="onRemoveFile($event)">
</FilePond>
```

I have the component with custom server handlers. Upload and revert works fine. 
My fileUploadServer config:
```ts
fileUploadServer =  {
  process: this.fileUploaderHandler.handleProcess,
  revert: this.fileUploaderHandler.handleRevert,
  restore: this.fileUploaderHandler.handleRestore,
  load: this.fileUploaderHandler.handleLoad
}
```

When I open the form in "edit" mode, I inject files as an array of file names, but I'm not able to override the load method. It always makes a request against ```http://localhost:4200/my-file-name.pdf```. 

I've tried overriding load, restore and fetch methods, but none of them get called.

I'm not sure if this is an only angular error, because it seems weird to me that process handler works well but load doesn't get called.

Filepond version: 1.4.0

**Comment by rikschennink** [comment]
The `load` and `restore` methods only get called for files added using the `files` array explicitly configured as `local` or `limbo` files.

More information here:
https://pqina.nl/filepond/docs/patterns/api/filepond-object/#setting-initial-files

I think FilePond is loading the files using XMLHttpRequest and as it can't find them so throws a 404.

**Comment by aitorllj93** [comment]
Thank you, that works :+1:
