### ISSUE TITLE
Cannot understand the api fully.

### ISSUE THREAD

**Issue by Akku-21** [pqina/angular-filepond#4]
Hello,
let me first say that I really like the filepond library and thank you for your work. I now have an issue understanding the documentation. So far implemented filepond in my angular app and wrote a backend. The fileupload works in that files end up in a temporary folder on the server. My issue is now with the points  

5. client submits the FilePond parent form containing the hidden input field with the unique id
6. server uses the unique id to move tmp/12345/my-file.jpg to its final location and remove the tmp/12345 folder

of the documentation. As I understand I will have to wrap the <file-pond> in a <form> and handle the submit myself. Can you maybe put an example for this into the docs. 

regards Akku

**Comment by rikschennink** [comment]
Hi, this is outside of the scope of FilePond. 

It would require a basic form submit to your server, the submit will then contain the file ids of the files that were uploaded in the FilePond component, your server can then move the files.

Example code: https://github.com/pqina/filepond-boilerplate-php

**Comment by Akku-21** [comment]
Thanks for the quick answer.  How can i get the id in a submit form using angular. Although this is out of scope, I am hoping you could offer me a small snipped. 
thanks in advance
regards Akku

**Comment by rikschennink** [comment]
if you use a form tag, the form POST will contain all field values inside the form.
