### ISSUE TITLE
Filepond Upload Status shows “Upload Complete” before the file is uploaded

### ISSUE THREAD

**Issue by amitusc** [pqina/angular-filepond#5]
I am uploading a file to S3 bucket as soon as its dropped to FilePond container but the status shows complete even if the S3 upload function is still uploading the file

**Comment by rikschennink** [comment]
This adapter has been deprecated in favor of https://github.com/pqina/ngx-filepond please use that one instead. 

Note that this is issue most likely doesn't seem related to any adapter but most likely is related to your upload method used.
