### ISSUE TITLE
Angular FilePond not loading FilePond css

### ISSUE THREAD

**Issue by Ryukote** [pqina/angular-filepond#7]
Hi,

I am trying to use FilePond with Angular, but for some reason app is not loading css of FilePond.
What I have done is installed filepond and ngx-filepond via npm and I can use FilePondModule without any problems, but css is not loading. 

I have included node_modules path to min.css file inside angular.json and used 'filePondStyle' for class in the component I am calling FilePond component.

I also believe that is the reason why loading animation for the file is being infinite which is also the problem I have.

I think I am probably missing something in the process, but I can't figure it out what exactly.
I don't care about FilePreview cause I am trying to upload pdf files.

**Comment by rikschennink** [comment]
This is a deprecated repository, please use https://github.com/pqina/ngx-filepond
