### ISSUE TITLE
can't get file and display it in my angular app

### ISSUE THREAD

**Issue by AbdooShawky** [pqina/angular-filepond#9]
Hello, currently I am using file-pond and I really like it.

I am trying to append a file from my assets folder to the file pond.
this is what I tried to do 

HTML:
` <file-pond 
                            #myPond 
                            [options]="pondOptions" 
                            (onaddfile)="pondHandleAddFile($event)"
                            [files]="pondFiles">
                        </file-pond>`

TS
`pondOptions: FilePondOptions = {
    allowMultiple: true,
    required: true,
    labelIdle: 'Drop files here...'
  };  
`
`pondFiles: FilePondOptions["files"] = [
    {
      source: '../../../../assets/img/image-preview.jpg',
      options: {
        type: 'local'
      }
    }
  ]
`
and this is what I get how can I fix this and make it load the file correctly
![image](https://user-images.githubusercontent.com/56520536/195830453-203d9ef5-529c-42a5-b7b7-982075dc2f9a.png)

I checked the URL of the image by displaying it in "img" tag and its working fine

**Comment by rikschennink** [comment]
You've marked the file as `'local'` which means FilePond will run the `server.load` routine to load the file from the local server, the idea being that `source` is set to a unique file id not a path.

Instead use `['source-of-file']`
